### PR TITLE
Delete active jobs for finished JobSets

### LINKED ISSUE #162: Delete active child jobs when jobset is considered failed
Currently we leave the jobs running to complete on their own, but this may not be desirable since we want the jobs to immediately release the resources they hold; so to be consistent with the Job API, we should delete all active jobs once the job succeeds or fails.

/kind bug

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Fixes #162 

Also fixes a bug in the `success policy 'all' with empty replicated jobs list` test case parameters (success policy target should be empty) which had somehow slipped our test logic until I added these changes to the controller.

### CODE REVIEW

File: test/integration/controller/jobset_controller_test.go [hunk 1]
```diff
@@ -740,6 +782,36 @@ func checkExpectedServices(js *jobset.JobSet) {
 	}).Should(gomega.Equal(numExpectedServices(js)))
 }
 
+// Check one headless service per job was created successfully.
```
Comment (ahg-g) [inline test/integration/controller/jobset_controller_test.go:785]: wrong comment

Comment (danielvegamyhre) [reply test/integration/controller/jobset_controller_test.go]: fixed
