### PR TITLE
Add `jobset.sigs.k8s.io/priority` to all child Pods to fix bug in exclusive placement.

### LINKED ISSUE #1057: `alpha.jobset.sigs.k8s.io/exclusive-topology` doesn't work with jobsets without exclusive-topology
**What happened**: We have jobsets with `alpha.jobset.sigs.k8s.io/exclusive-topology: nodepool` and jobsets without `alpha.jobset.sigs.k8s.io/exclusive-topology`. Pods from the former and latter jobsets are placed on the same nodepool.

**What you expected to happen**: Pods from the former should block any jobset pods to land on the same nodepool. Pods from the former should avoid nodes that already have some running jobset pods, regardless of whether those jobset pods using exclusive-topologyor not..

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- JobSet version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by GiuseppeTT**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Add `jobset.sigs.k8s.io/priority` to all child Pods to fix bug in exclusive placement.

#### Which issue(s) this PR fixes:

Fixes #1057

#### Does this PR introduce a user-facing change?

```release-note
Add `jobset.sigs.k8s.io/priority` to all child Pods to fix bug in exclusive placement.
```

### CODE REVIEW

**Comment by GiuseppeTT** [comment]
I also did a manual test to confirm it fixes the bug

```bash
# Create VIP JobSet that should have exclusive access to all node pools (3 in my case)
kubectl apply -f - <<EOF
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: vip-jobset
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  replicatedJobs:
  - name: workers
    replicas: 3
    template:
      spec:
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: busybox
              command: ['/bin/sh', '-c']
              args:
              - |
                echo "Start"
                sleep infinity
EOF

# Create a common JobSet that should not be able to schedule its Pods since the VIP JobSet is using all Node pools
kubectl apply -f - <<EOF
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: common-jobset
spec:
  replicatedJobs:
  - name: workers
    replicas: 1
    template:
      spec:
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: busybox
              command: ['/bin/sh', '-c']
              args:
              - |
                echo "Start"
                sleep infinity
EOF

# Check node assignment
kubectl get pod -o wide

# Check reason
kubectl describe pod common-jobset-workers-0-0-45rdk
```

Node assignment

```
NAME                              READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
common-jobset-workers-0-0-45rdk   0/1     Pending   0          51s   <none>       <none>   <none>           <none>
common-jobset-workers-0-1-5j2ms   0/1     Pending   0          51s   <none>       <none>   <none>           <none>
vip-jobset-workers-0-0-cz74d      1/1     Running   0          65s   10.100.5.5   A        <none>           <none>
vip-jobset-workers-0-1-cvcdr      1/1     Running   0          64s   10.100.6.6   B        <none>           <none>
vip-jobset-workers-1-0-82pq4      1/1     Running   0          65s   10.100.4.5   C        <none>           <none>
vip-jobset-workers-1-1-6rm4g      1/1     Running   0          64s   10.100.3.6   D        <none>           <none>
vip-jobset-workers-2-0-85np2      1/1     Running   0          65s   10.100.8.6   E        <none>           <none>
vip-jobset-workers-2-1-l55vl      1/1     Running   0          64s   10.100.7.7   F        <none>           <none>
```

Reason of pending

```
Events:
  Type     Reason             Age   From                Message
  ----     ------             ----  ----                -------
  Warning  FailedScheduling   15s   default-scheduler   0/6 nodes are available: 6 node(s) didn't satisfy existing pods anti-affinity rules. preemption: 0/6 nodes are available: 6 No preemption victims found for incoming pod.
```

File: pkg/webhooks/pod_mutating_webhook.go [hunk 1]
```diff
@@ -183,11 +192,10 @@ func (p *podWebhook) topologyFromPod(ctx context.Context, pod *corev1.Pod, topol
 	log := ctrl.LoggerFrom(ctx)
 
 	nodeName := pod.Spec.NodeName
-	ns := pod.Namespace
 
 	// Get node the leader pod is running on.
 	var node corev1.Node
-	if err := p.client.Get(ctx, types.NamespacedName{Name: nodeName, Namespace: ns}, &node); err != nil {
+	if err := p.client.Get(ctx, types.NamespacedName{Name: nodeName}, &node); err != nil {
```
Comment (GiuseppeTT) [inline pkg/webhooks/pod_mutating_webhook.go:198]: I took the opportunity to remove the namespace of the get request for the node since it's a cluster scoped resource
