### PR TITLE
Automatically move generated client-go files to repo root

### LINKED ISSUE #219: Bug: Changing the API and regenerating client-go does not add changes to code repo.
When I modify the api and try to generate client-go, my client-go is generated and placed in my go src directory (ie /home/ec2-user/go/1.20.2/src/sigs.k8s.io/jobset/client-go/).  

I think that it should go to client-go folder in the repo.  Currently if I modify the API I would have to copy /home/ec2-user/go/1.20.2/src/sigs.k8s.io/jobset/client-go/ and rewrite the folder in client-go.  

This is not ideal.  

Any ideas on what is going wrong?

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Fixes #219

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
@kannon92 Can you checkout this PR locally, try generating the client-go files, and let me know if the fix works?

**Comment by kannon92** [comment]
> @kannon92 Can you checkout this PR locally, try generating the client-go files, and let me know if the fix works? It works for me locally when I clone jobset into /tmp folder, delete `/tmp/jobset/client-go` then run `make generate`, the client-go files appear in `/tmp/jobset/client-go`.

Doing this now!

File: hack/update-codegen.sh [hunk 1]
```diff
@@ -21,10 +21,29 @@ set -o pipefail
...
+echo "GOPATH=$GOPATH"
 
 bash "${CODEGEN_PKG}/generate-groups.sh" \
   "all" \
   sigs.k8s.io/jobset/client-go \
   sigs.k8s.io/jobset/api \
   jobset:v1alpha2 \
   --go-header-file ./boilerplate.go.txt
+
+# if client-go files were generated outside of repo root, attempt to move them to the repo root.
```
Comment (kannon92) [inline hack/update-codegen.sh:35]: Testing this, it works but you will have to delete your `client-go` directory in order to get the copy to work.  its a bit odd.

Can we just overwrite if we assume that these changes will never be modified manually?

I deleted everything under `client-go` directory but I reread your script and it wouldn't copy those changes so I had to delete the `client-go` directory also.  

Maybe we just assume anything in client-go can be purged if you are running this?

Comment (danielvegamyhre) [reply hack/update-codegen.sh:35]: I added a force flag to the mv command so that it will overwrite if necessary. I think it's fine to assume the generated files will be overwritten/purged.

Comment (kannon92) [reply hack/update-codegen.sh:35]: The issue is this code:

```
if [ ! -d "$REPO_ROOT/client-go" ]; then
```
This is saying that if the folder exists then we won't copy it.  

Maybe we just remove this if check?

Comment (danielvegamyhre) [reply hack/update-codegen.sh:35]: Oh I see what you mean now - thanks! I removed this check and also added a check before moving the files to only move it if it isn't already in the repo root (since if that is the case, the mv command will fail even with the force flag).

**Comment by kannon92** [comment]
/lgtm

Thanks for fixing this!
