### PR TITLE
Default service name in JobSet controller

### LINKED ISSUE #394: Jobset Controller Crashes if no spec.network is set
Jobset version: `registry.k8s.io/jobset/jobset:v0.3.1`
```bash
❯ kubectl version
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1286000
```

Installed as described in [Install a released version](https://github.com/kubernetes-sigs/jobset/blob/main/docs/setup/install.md#install-a-released-version) with no modifications

```yaml
# jobset-sample.yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  generateName: sleep-job-
  labels:
    kueue.x-k8s.io/queue-name: default-local-queue
spec:
  suspend: true
  replicatedJobs:
    - name: workers
      replicas: 1
      template:
        spec:
          parallelism: 2
          completions: 2
          backoffLimit: 0
          template:
            spec:
              nodeSelector:
                node_pool: default-pool
              containers:
                - name: sleep
                  image: busybox
                  resources:
                    requests:
                      cpu: 1
                      memory: "200Mi"
                    limits:
                      cpu: 1
                      memory: "200Mi"
                  command:
                    - sleep
                  args:
                    - 60s
    - name: driver
      template:
        spec:
          parallelism: 1
          completions: 1
          backoffLimit: 0
          template:
            spec:
              nodeSelector:
                node_pool: gpu-pool
              containers:
                - name: sleep
                  image: busybox
                  resources:
                    requests:
                      cpu: 1
                      memory: "200Mi"
                    limits:
                      cpu: 1
                      memory: "200Mi"
                  command:
                    - sleep
                  args:
                    - 60s

```

Produces the following error when executing `kubectl create -f JobSet.yaml`

```txt
2024-02-02T09:23:31Z	LEVEL(-2)	Reconciling JobSet	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "b74be97c-3e4b-4b0e-b613-bab40c8f36d9", "jobset": {"name":"sleep-job-p4v5n","namespace":"default"}}
2024-02-02T09:23:31Z	ERROR	creating jobs	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "b74be97c-3e4b-4b0e-b613-bab40c8f36d9", "jobset": {"name":"sleep-job-p4v5n","namespace":"default"}, "error": "a subdomain should be set if dns hostnames are enabled"}
sigs.k8s.io/jobset/pkg/controllers.(*JobSetReconciler).Reconcile
	/workspace/pkg/controllers/jobset_controller.go:149
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2024-02-02T09:23:31Z	ERROR	Reconciler error	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "b74be97c-3e4b-4b0e-b613-bab40c8f36d9", "error": "a subdomain should be set if dns hostnames are enabled"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2024-02-02T09:23:31Z	LEVEL(-2)	Reconciling JobSet	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "e1d0230b-bac0-44f1-a2f5-f253a353c865", "jobset": {"name":"sleep-job-p4v5n","namespace":"default"}}
2024-02-02T09:23:31Z	ERROR	creating jobs	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "e1d0230b-bac0-44f1-a2f5-f253a353c865", "jobset": {"name":"sleep-job-p4v5n","namespace":"default"}, "error": "a subdomain should be set if dns hostnames are enabled"}
sigs.k8s.io/jobset/pkg/controllers.(*JobSetReconciler).Reconcile
	/workspace/pkg/controllers/jobset_controller.go:149
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2024-02-02T09:23:31Z	ERROR	Reconciler error	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"sleep-job-p4v5n","namespace":"default"}, "namespace": "default", "name": "sleep-job-p4v5n", "reconcileID": "e1d0230b-bac0-44f1-a2f5-f253a353c865", "error": "a subdomain should be set if dns hostnames are enabled"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
```

Adding 
```
spec:
  network:
    enableDNSHostnames: false
```
fixes the issue

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Fixes #394

### CODE REVIEW

File: pkg/controllers/jobset_controller.go [hunk 1]
```diff
@@ -368,11 +368,6 @@ func (r *JobSetReconciler) createJobs(ctx context.Context, js *jobset.JobSet, ow
 
 	// If pod DNS hostnames are enabled, create a headless service for the JobSet
 	if dnsHostnamesEnabled(js) {
-
-		// Don't try to create a headless service without a subdomain
-		if js.Spec.Network.Subdomain == "" {
-			return fmt.Errorf("a subdomain should be set if dns hostnames are enabled")
-		}
```
Comment (ahg-g) [inline pkg/controllers/jobset_controller.go:375]: better to set `js.Spec.Network.Subdomain = js.Name` if empty in the top level function Reconcile so that we don't need to do this check everywhere.

The e2e tests are failing because you didn't change https://github.com/kubernetes-sigs/jobset/blob/45429d558afa45813fc19c86991b13a17470b694/pkg/controllers/jobset_controller.go#L616C3-L616C35

Comment (danielvegamyhre) [reply pkg/controllers/jobset_controller.go:375]: Good catch, thanks! Done.

**Comment by kannon92** [comment]
@danielvegamyhre after this merge, I am seeing errors in the logs in our `createJobs`.

I see the following in the logs:

```
  2024-02-06T18:46:10-05:00     ERROR   creating jobs   {"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"test-js","namespace":"jobset-ns-stqcv"}, "namespace": "jobset-ns-stqcv", "name": "test-js", "reconcileID": "4250eb7e-1660-4af4-a3b0-873b93aa85a4", "jobset": {"name":"test-js","namespace":"jobset-ns-stqcv"}, "error": "Service \"\" is invalid: metadata.name: Required value: name or generateName is required"}
```

**Comment by danielvegamyhre** [comment]
> @danielvegamyhre after this merge, I am seeing errors in the logs in our `createJobs`.
> 
> I see the following in the logs:
> 
> ```
>   2024-02-06T18:46:10-05:00     ERROR   creating jobs   {"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"test-js","namespace":"jobset-ns-stqcv"}, "namespace": "jobset-ns-stqcv", "name": "test-js", "reconcileID": "4250eb7e-1660-4af4-a3b0-873b93aa85a4", "jobset": {"name":"test-js","namespace":"jobset-ns-stqcv"}, "error": "Service \"\" is invalid: metadata.name: Required value: name or generateName is required"}
> ```

Can you paste that into an issue? I will take a look, thanks for bringing this up
